/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package martopediareal;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;


/**
 *
 * @author zobia
 */
public class Getting_IN extends javax.swing.JFrame {

    PreparedStatement pst=null;  //default
    private JFrame frame;
    

    /**
     * Creates new form Getting_IN
     */
    public Getting_IN() {
        initComponents();
        
        this.signUpHeadLabel.setVisible(false);  //These components will not be visible initially when the application runs
        this.emailIconLabel.setVisible(false);
        this.SignUpButton.setVisible(false);
        hidePassLabel.setVisible(false);
        
    }

    int xx,xy;  //initialised x and y coordinates to move the panel 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        SignUpButton = new javax.swing.JButton();
        BackButton = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JLabel();
        emailIconLabel = new javax.swing.JLabel();
        signUpHeadLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        movingPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        hidePassLabel = new javax.swing.JLabel();
        showPassLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        emailID = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();
        lab7 = new javax.swing.JLabel();
        forgotPasswordLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        loginLabelButton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        signUpLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mainPanelMouseDragged(evt);
            }
        });
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainPanelMouseReleased(evt);
            }
        });
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpButton.setBackground(new java.awt.Color(255, 153, 0));
        SignUpButton.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(51, 51, 51));
        SignUpButton.setText("Sign up");
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseExited(evt);
            }
        });
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        mainPanel.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 453, 120, 40));

        BackButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackButton.setToolTipText("Go Back?");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackButtonMousePressed(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackButtonMouseExited(evt);
            }
        });
        mainPanel.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(0, 255, 255));
        ExitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exitWhite.png"))); // NOI18N
        ExitButton.setToolTipText("Exit");
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitButtonMousePressed(evt);
            }
        });
        mainPanel.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 50, 50));

        emailIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/email.png"))); // NOI18N
        mainPanel.add(emailIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 80, 80));

        signUpHeadLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        signUpHeadLabel.setForeground(new java.awt.Color(255, 255, 255));
        signUpHeadLabel.setText("Sign up");
        mainPanel.add(signUpHeadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 230, 50));

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        movingPanel.setBackground(new java.awt.Color(51, 51, 51));
        movingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        movingPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 220, 20));

        hidePassLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye visible.png"))); // NOI18N
        hidePassLabel.setToolTipText("View Password");
        hidePassLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hidePassLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePassLabelMousePressed(evt);
            }
        });
        movingPanel.add(hidePassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 60, 50));

        showPassLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye-invisible.gif"))); // NOI18N
        showPassLabel.setToolTipText("Hide Password");
        showPassLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPassLabelMousePressed(evt);
            }
        });
        movingPanel.add(showPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 60, 50));
        movingPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 190, 10));

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        movingPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 10));

        emailID.setBackground(new java.awt.Color(51, 51, 51));
        emailID.setForeground(new java.awt.Color(155, 155, 155));
        emailID.setText("Email ID");
        emailID.setToolTipText("Enter your Email address");
        emailID.setBorder(null);
        emailID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        emailID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailIDFocusLost(evt);
            }
        });
        emailID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailIDKeyTyped(evt);
            }
        });
        movingPanel.add(emailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 220, 30));

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setForeground(new java.awt.Color(155, 155, 155));
        jPasswordField1.setText("Password");
        jPasswordField1.setToolTipText("Enter Password");
        jPasswordField1.setBorder(null);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        movingPanel.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 190, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/locked.png"))); // NOI18N
        movingPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 70, 70));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginButton.setBackground(new java.awt.Color(255, 153, 0));
        LoginButton.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(51, 51, 51));
        LoginButton.setText("Login");
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtonMouseExited(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel5.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, 30));

        movingPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 270, 50));

        loginLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("Login");
        movingPanel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, 50));

        lab7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User_1.png"))); // NOI18N
        movingPanel.add(lab7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 80));

        forgotPasswordLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        forgotPasswordLabel.setForeground(new java.awt.Color(204, 204, 204));
        forgotPasswordLabel.setText("Forgot Password?");
        forgotPasswordLabel.setToolTipText("Click to reset Password");
        forgotPasswordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forgotPasswordLabelMousePressed(evt);
            }
        });
        movingPanel.add(forgotPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        mainPanel.add(movingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 320, 440));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        loginLabelButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        loginLabelButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabelButton.setText("LOGIN");
        loginLabelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLabelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginLabelButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLabelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLabelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 140, 50));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpLabel.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        signUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpLabel.setText("SIGN UP");
        signUpLabel.setToolTipText("Click to create an account");
        signUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signUpLabelMousePressed(evt);
            }
        });
        jPanel3.add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        mainPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 140, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Getting_In.jpg"))); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseEntered
        // When the cursor is on the SignUp Button
        SignUpButton.setBackground(new Color(155,155,155));  //Color changes again to a different one from the above
    }//GEN-LAST:event_SignUpButtonMouseEntered

    private void SignUpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseExited
        //When the cursor is removed from the SignUpButton
        SignUpButton.setBackground(new Color(255,153,0));  //Color of sign up button changes
    }//GEN-LAST:event_SignUpButtonMouseExited

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        //When Sign Up button is pressed
        String Email=emailID.getText();  //User's email id is stored in this variable Email and
        String Password=jPasswordField1.getText();  //User's password is stored in this variable Password

        if(Email.isEmpty() && Password.isEmpty())  //This checks if BOTH Email and password fields are empty
        {
            JOptionPane.showMessageDialog(this,"Please enter Email address and Password");
        }

        else if(Email.isEmpty())  //This checks if ONLY Email is empty
        {
            JOptionPane.showMessageDialog(this,"Please enter Email address");
        }

        else if(Password.isEmpty())  //This checks if ONLY Password is empty
        {
            JOptionPane.showMessageDialog(this,"Please enter Password");
        }

        else if(Email.contains("@") && Email.contains("."))  //This checks if the email address comtains @ and . (dot)
        {
            new Registration().setVisible(true);  //form called Registration open
            this.dispose();  //current form is closed
            Registration.emailID.setText(this.emailID.getText());  //Gets the email Id from emailID field in this form and displays it on the emailID field in the Registration form
        }

        else
        {
            JOptionPane.showMessageDialog(null, "Email ID is not valid."+'\n'+"Please Try Again!");  //otherwise this displays the message that email ID is not valid.
            // Please Try Again!
        }
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void BackButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMousePressed
        // Once the Back Button is pressed
        new MainPage().setVisible(true);  //form called MainPage opens and
        this.dispose();  //the current form closes
    }//GEN-LAST:event_BackButtonMousePressed

    private void BackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseEntered
        // When the cursor is on the Exit label-Button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.white);  //Border of Back label changes to white to highlight it - but is not applied yet
        BackButton.setBorder(Label_Border);  //the above change is then applied to the Back Button
    }//GEN-LAST:event_BackButtonMouseEntered

    private void BackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseExited
        // When the cursor is moved away from the Back label-Button:
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,new Color(155,155,155));  //Border of Back label changes back to black - but is not applied yet
        BackButton.setBorder(Label_Border);  //the above change is then applied to the Back Button
    }//GEN-LAST:event_BackButtonMouseExited

    private void ExitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMousePressed
        //When the Exit button is pressed
        frame = new JFrame("Exit");  //New small frame is created to show exit warning
        if (JOptionPane.showConfirmDialog(frame, "Do you want to Exit?","MARTOPEDIA",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)  //It displays YES/NO option for the user to select;
        {
            //gets inside if the user selects YES
            System.exit(0);  //This code helps to close any form/application
        }
    }//GEN-LAST:event_ExitButtonMousePressed

    private void ExitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseEntered
        //When the cursor is on the Exit label-Button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.white);  //Border of exit label changes to white to highlight it - but is not applied yet
        ExitButton.setBorder(Label_Border);  //the above change is then applied to the Exit Button
    }//GEN-LAST:event_ExitButtonMouseEntered

    private void ExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseExited
        //When the cursor is removed from the Exit label-Button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.black);  //Border of exit label changes back to black but is not applied yet
        ExitButton.setBorder(Label_Border);  //the above change is then applied to the Exit Button
    }//GEN-LAST:event_ExitButtonMouseExited

    private void hidePassLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassLabelMousePressed
        //When hidePass Label button is clicked
        showPassLabel.setVisible(true);  //show pass label-button becomes visible, making
        hidePassLabel.setVisible(false);  //the hide pass label-button invisible and
        jPasswordField1.setEchoChar('*');  //Since it is to hide the password, all the characters in the password will be converted to *
    }//GEN-LAST:event_hidePassLabelMousePressed

    private void showPassLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPassLabelMousePressed
        //When showPass Label button is clicked
        hidePassLabel.setVisible(true);  //the hide pass label-button becomes visible, making
        showPassLabel.setVisible(false);  //the show pass label-button invisible and
        jPasswordField1.setEchoChar((char)0);  //Since it is to show the password, all the * in the password will be converted to character values- meaning the characters will be visible
    }//GEN-LAST:event_showPassLabelMousePressed

    private void emailIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailIDFocusGained
        //This code runs when the curson is on the email ID field
        if(emailID.getText().trim().equals("Email ID"))   //If there is default "Email ID" then
        {
            emailID.setText("");  // "Email ID" will be removed so that users can type their Email IDs
            emailID.setForeground(Color.white);  //foreground color of the field becomes white
        }
    }//GEN-LAST:event_emailIDFocusGained

    private void emailIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailIDFocusLost
        // When the cursor is moved away from the email ID field
        if(emailID.getText().trim().equals("") ||  emailID.getText().trim().equals("Email ID"))  //If there is nothing entered by the user and default "Email ID" is visible then
        {
            emailID.setText("Email ID");  // "Email ID" will continue to show
            emailID.setForeground(new Color(155,155,155));  //and it will set the foreground color of the email ID field to black
        }
    }//GEN-LAST:event_emailIDFocusLost

    private void emailIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailIDKeyTyped
        // When Email is typed in the email field
        if (emailID.getText().length() >= 255 )   // limit to 255 characters; Email ID cannot be greater than 255 characters
        {
            evt.consume();
        }
    }//GEN-LAST:event_emailIDKeyTyped

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        //This code runs when the curson is on the password field
        String pass = String.valueOf(jPasswordField1.getPassword());

        if(pass.trim().equals("Password"))  //If there is default "Password" then
        {
            jPasswordField1.setText("");  // "Password" will be removed so that users can type their passwords
            jPasswordField1.setForeground(Color.white);  //foreground color of the field becomes white
        }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        //This code runs when the curson is moved away from the password field
        String pass = String.valueOf(jPasswordField1.getPassword());

        if(pass.trim().equals("") || pass.trim().equals("Password"))  //If there is nothing entered by the user and default "Password" is visible then
        {
            jPasswordField1.setText("Password");  // "Password" will continue to show
            jPasswordField1.setForeground(new Color(155,155,155));  //and it will set the foreground color of the password field to black
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void LoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseEntered
        // When the cursor in on the Login button its color changes
        LoginButton.setBackground(new Color(155,155,155));
    }//GEN-LAST:event_LoginButtonMouseEntered

    private void LoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseExited
        // When the cursor is removed from the Login button its color is changed
        LoginButton.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_LoginButtonMouseExited

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // Following happens when Login Buttton is pressed
        String email=emailID.getText();
        String pass=jPasswordField1.getText();

        try
        {
            Connection con = (Connection)  //To establish relation with the database
            DriverManager.getConnection ("jdbc:mysql://localhost:3306/Martopedia","root", "abc.123$");

            String query = "SELECT Email,Password FROM AllUsers WHERE Email= ? AND Password= ?";  //Query to extract the wanted data from database
            pst = con.prepareStatement(query);
            pst.setString(1,emailID.getText());
            pst.setString(2,jPasswordField1.getText());

            ResultSet rs=pst.executeQuery();

            if(rs.next())  //if the entered email ID and pass exists in database then
            {
                new UserInterface().setVisible(true);  //form called UserInterface will open
                 UserInterface.emailLabel.setText(this.emailID.getText());
                this.dispose();  //current form will be closed
            }      
            
          }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void forgotPasswordLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLabelMousePressed
        //When forgot password label-button is pressed:
        new forgotPassword().setVisible(true);  //form called NewPassword1 opens
        this.dispose();  //current form is closed
    }//GEN-LAST:event_forgotPasswordLabelMousePressed

    private void loginLabelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelButtonMousePressed
        // Following code runs when login label-button is pressed - to bring the moving panel back to its original position
        int panel=this.movingPanel.getX();  //gets the X-axis of the panel

        if(panel>-1)
        {
            Animacion.Animacion.mover_izquierda(428,110,2,3,movingPanel);  //function to place the moving panel on specified coordinates
        }

        jPanel6.setVisible(false);  // These components will become invisible
        signUpHeadLabel.setVisible(false);
        emailIconLabel.setVisible(false);
        SignUpButton.setVisible(false);

        LoginButton.setVisible(true);  // These components will become visible
        lab7.setVisible(true);
        loginLabel.setVisible(true);
        forgotPasswordLabel.setVisible(true);
        hidePassLabel.setVisible(true);
        showPassLabel.setVisible(true);
    }//GEN-LAST:event_loginLabelButtonMousePressed

    private void signUpLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMousePressed
        // Following code runs when Sign up label-button is pressed
        int panel=this.movingPanel.getX();  //this code gets the X-axis of the moving panel

        if(panel>-1)  //X-axis should be greater than -1 because moving it to the right side where X will be positive
        {
            Animacion.Animacion.mover_derecha(110,428,2,3,movingPanel);  
        }

        LoginButton.setVisible(false);  //These components become invisible once the above code runs and
        lab7.setVisible(false);
        loginLabel.setVisible(false);
        forgotPasswordLabel.setVisible(false);
        hidePassLabel.setVisible(false);
        showPassLabel.setVisible(false);

        jPanel6.setVisible(true);  //These components become visible instead
        signUpHeadLabel.setVisible(true);
        emailIconLabel.setVisible(true);
        SignUpButton.setVisible(true);

    }//GEN-LAST:event_signUpLabelMousePressed

    private void mainPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseDragged
        // TODO add your handling code here:
        int x,y;
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_mainPanelMouseDragged

    private void mainPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMousePressed
        //When this current form (Getting_In)  runs, users can drag it to any corner of their screen,
        setOpacity((float)0.7);  //While dragging the opacity of the form decreases
        xx = evt.getX();  // X coordinates of the form's new position will be saved in this variable xx and
        xy = evt.getY();  // Y coordinates of the form's new position will be saved in this variable xy
    }//GEN-LAST:event_mainPanelMousePressed

    private void mainPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseReleased
        //After the form is dragged to a new position and the mouse button is released
        setOpacity((float)1.0);  //Its opacity comes back to normal
    }//GEN-LAST:event_mainPanelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Getting_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Getting_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Getting_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Getting_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Getting_IN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackButton;
    private javax.swing.JLabel ExitButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton SignUpButton;
    public static javax.swing.JTextField emailID;
    private javax.swing.JLabel emailIconLabel;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JLabel hidePassLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lab7;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLabelButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel movingPanel;
    private javax.swing.JLabel showPassLabel;
    private javax.swing.JLabel signUpHeadLabel;
    private javax.swing.JLabel signUpLabel;
    // End of variables declaration//GEN-END:variables
}
