/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package martopediareal;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author zobia
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        
        jPanel_aboutIn.setBackground(new Color(255,255,255,200));  //sets the colour of inner panel of About panel
        jPanel_contactIN.setBackground(new Color(255,255,255,150));  //sets the colour of inner panel of Contact panel
    }

         int xx,xy;
         
      public void switchPanels(JPanel panel)  //This is created so that the panels can move whenever "switchPanels" function is called later in other codes
     {
         jLayeredPane1.removeAll();
         jLayeredPane1.add(panel);
         jLayeredPane1.repaint();
         jLayeredPane1.revalidate();        
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        homePanel = new javax.swing.JPanel();
        nextLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        homeButton_homePanel = new javax.swing.JButton();
        aboutButton_homePanel = new javax.swing.JButton();
        contactButton_homePanel = new javax.swing.JButton();
        location_homePanel = new javax.swing.JButton();
        background_Label = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        exitLabel_about = new javax.swing.JLabel();
        jPanel_aboutIn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        homeButton_aboutPanel = new javax.swing.JButton();
        aboutButton_aboutPanel = new javax.swing.JButton();
        contactButton_aboutPanel = new javax.swing.JButton();
        location_aboutPanel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        contactPanel = new javax.swing.JPanel();
        BackButton_Contact = new javax.swing.JLabel();
        homeButton_contactPanel = new javax.swing.JButton();
        aboutButton_contactPanel = new javax.swing.JButton();
        contactButton_contactPanel = new javax.swing.JButton();
        location_contactPanel = new javax.swing.JButton();
        jPanel_contactIN = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        locationPanel = new javax.swing.JPanel();
        homeButton_locationPanel = new javax.swing.JButton();
        aboutButton_locationPanel = new javax.swing.JButton();
        contactButton_locationPanel = new javax.swing.JButton();
        location_locationPanel = new javax.swing.JButton();
        BackButton_Location = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nextLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PlayICON.png"))); // NOI18N
        nextLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextLabelMousePressed(evt);
            }
        });
        homePanel.add(nextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 160, 150));

        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exitWhite.png"))); // NOI18N
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitLabelMousePressed(evt);
            }
        });
        homePanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 40, 40));

        homeButton_homePanel.setBackground(new java.awt.Color(153, 255, 255));
        homeButton_homePanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        homeButton_homePanel.setForeground(new java.awt.Color(51, 51, 51));
        homeButton_homePanel.setText("Home");
        homeButton_homePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton_homePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton_homePanelActionPerformed(evt);
            }
        });
        homePanel.add(homeButton_homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        aboutButton_homePanel.setBackground(new java.awt.Color(153, 255, 255));
        aboutButton_homePanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        aboutButton_homePanel.setForeground(new java.awt.Color(51, 51, 51));
        aboutButton_homePanel.setText("About Us");
        aboutButton_homePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutButton_homePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButton_homePanelActionPerformed(evt);
            }
        });
        homePanel.add(aboutButton_homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        contactButton_homePanel.setBackground(new java.awt.Color(153, 255, 255));
        contactButton_homePanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        contactButton_homePanel.setForeground(new java.awt.Color(51, 51, 51));
        contactButton_homePanel.setText("Get in touch");
        contactButton_homePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactButton_homePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactButton_homePanelActionPerformed(evt);
            }
        });
        homePanel.add(contactButton_homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, -1));

        location_homePanel.setBackground(new java.awt.Color(153, 255, 255));
        location_homePanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        location_homePanel.setForeground(new java.awt.Color(51, 51, 51));
        location_homePanel.setText("Locations");
        location_homePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        location_homePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location_homePanelActionPerformed(evt);
            }
        });
        homePanel.add(location_homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 120, -1));

        background_Label.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        background_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Homepage.jpg"))); // NOI18N
        homePanel.add(background_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));

        jLayeredPane1.add(homePanel, "card2");

        aboutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitLabel_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabel_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabel_aboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitLabel_aboutMousePressed(evt);
            }
        });
        aboutPanel.add(exitLabel_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 10, 40, 50));

        jPanel_aboutIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Our");
        jPanel_aboutIn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 70, 60));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("you always");
        jPanel_aboutIn.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 110, 50));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Welcome to a better delivery service in the UAE.");
        jPanel_aboutIn.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 50));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("A grocery delivery service that works for the customer, not against him.");
        jPanel_aboutIn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 650, 60));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("with the store.");
        jPanel_aboutIn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 630, 80));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("We opened our door in 2008 and since then have been launching, positioning ");
        jPanel_aboutIn.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 630, 70));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("and elevating brands throughout the Middle East, North Africa and beyond. We");
        jPanel_aboutIn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 630, 80));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("create experiences that strengthen relationships between our customers and the ");
        jPanel_aboutIn.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 630, 90));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grocery Clipart.png"))); // NOI18N
        jPanel_aboutIn.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 330, 230));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("people that matter most to them.");
        jPanel_aboutIn.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 630, 100));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("recipes.");
        jPanel_aboutIn.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 630, 130));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("and encourage overlap  so");
        jPanel_aboutIn.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 630, 110));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("We sign stores based on your wishes ");
        jPanel_aboutIn.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 630, 100));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("have a choice, we constantly update");
        jPanel_aboutIn.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 630, 100));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("our product lists so you don't have to");
        jPanel_aboutIn.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 630, 110));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("Customer Service personnel are trained to be YOUR advocates when dealing ");
        jPanel_aboutIn.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 630, 70));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("compromise on your grandma's favorite");
        jPanel_aboutIn.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 630, 120));

        aboutPanel.add(jPanel_aboutIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 640, 470));

        homeButton_aboutPanel.setBackground(new java.awt.Color(153, 255, 255));
        homeButton_aboutPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        homeButton_aboutPanel.setForeground(new java.awt.Color(51, 51, 51));
        homeButton_aboutPanel.setText("Home");
        homeButton_aboutPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton_aboutPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton_aboutPanelActionPerformed(evt);
            }
        });
        aboutPanel.add(homeButton_aboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        aboutButton_aboutPanel.setBackground(new java.awt.Color(153, 255, 255));
        aboutButton_aboutPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        aboutButton_aboutPanel.setForeground(new java.awt.Color(51, 51, 51));
        aboutButton_aboutPanel.setText("About Us");
        aboutButton_aboutPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutButton_aboutPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButton_aboutPanelActionPerformed(evt);
            }
        });
        aboutPanel.add(aboutButton_aboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        contactButton_aboutPanel.setBackground(new java.awt.Color(153, 255, 255));
        contactButton_aboutPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        contactButton_aboutPanel.setForeground(new java.awt.Color(51, 51, 51));
        contactButton_aboutPanel.setText("Get in touch");
        contactButton_aboutPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactButton_aboutPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactButton_aboutPanelActionPerformed(evt);
            }
        });
        aboutPanel.add(contactButton_aboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, -1));

        location_aboutPanel.setBackground(new java.awt.Color(153, 255, 255));
        location_aboutPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        location_aboutPanel.setForeground(new java.awt.Color(51, 51, 51));
        location_aboutPanel.setText("Locations");
        location_aboutPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        location_aboutPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location_aboutPanelActionPerformed(evt);
            }
        });
        aboutPanel.add(location_aboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 120, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about-us.png"))); // NOI18N
        aboutPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));

        jLayeredPane1.add(aboutPanel, "card3");

        contactPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton_Contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackButton_Contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exitWhite.png"))); // NOI18N
        BackButton_Contact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton_Contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackButton_ContactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackButton_ContactMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackButton_ContactMousePressed(evt);
            }
        });
        contactPanel.add(BackButton_Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 60, 40));

        homeButton_contactPanel.setBackground(new java.awt.Color(153, 255, 255));
        homeButton_contactPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        homeButton_contactPanel.setForeground(new java.awt.Color(51, 51, 51));
        homeButton_contactPanel.setText("Home");
        homeButton_contactPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton_contactPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton_contactPanelActionPerformed(evt);
            }
        });
        contactPanel.add(homeButton_contactPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        aboutButton_contactPanel.setBackground(new java.awt.Color(153, 255, 255));
        aboutButton_contactPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        aboutButton_contactPanel.setForeground(new java.awt.Color(51, 51, 51));
        aboutButton_contactPanel.setText("About Us");
        aboutButton_contactPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutButton_contactPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButton_contactPanelActionPerformed(evt);
            }
        });
        contactPanel.add(aboutButton_contactPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        contactButton_contactPanel.setBackground(new java.awt.Color(153, 255, 255));
        contactButton_contactPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        contactButton_contactPanel.setForeground(new java.awt.Color(51, 51, 51));
        contactButton_contactPanel.setText("Get in touch");
        contactButton_contactPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactButton_contactPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactButton_contactPanelActionPerformed(evt);
            }
        });
        contactPanel.add(contactButton_contactPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, -1));

        location_contactPanel.setBackground(new java.awt.Color(153, 255, 255));
        location_contactPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        location_contactPanel.setForeground(new java.awt.Color(51, 51, 51));
        location_contactPanel.setText("Locations");
        location_contactPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        location_contactPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location_contactPanelActionPerformed(evt);
            }
        });
        contactPanel.add(location_contactPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 120, -1));

        jPanel_contactIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(204, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(204, 0, 51));
        jPanel_contactIN.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 50));

        jLabel26.setFont(new java.awt.Font("Venus Rising", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 0, 51));
        jLabel26.setText("Get in Touch");
        jPanel_contactIN.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel27.setText("+971 4 867 9619");
        jPanel_contactIN.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 220, 130, 50));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 0, 51));
        jLabel28.setText("London");
        jPanel_contactIN.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 271, -1, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clock.png"))); // NOI18N
        jLabel29.setText(" 8:30 AM - 6:00 PM");
        jPanel_contactIN.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/house.png"))); // NOI18N
        jLabel30.setText(" Office 7008, JBC1, Jumeirah Lake Towers, Dubai, UAE.");
        jPanel_contactIN.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel31.setText("smartmartopedia@mart.org");
        jPanel_contactIN.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 200, 220, 40));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 0, 51));
        jLabel32.setText("Head Office – Dubai");
        jPanel_contactIN.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clock.png"))); // NOI18N
        jLabel33.setText(" 8:30 AM - 6:00 PM");
        jPanel_contactIN.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/house.png"))); // NOI18N
        jLabel34.setText(" Level 20, 50 Bank Street Canary Wharf, S14 5DA, UK.");
        jPanel_contactIN.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel35.setText("+44 56 7 942 0134");
        jPanel_contactIN.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 170, 50));

        contactPanel.add(jPanel_contactIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 640, 470));

        BG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Homepage_contact.jpg"))); // NOI18N
        contactPanel.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));

        jLayeredPane1.add(contactPanel, "card4");

        locationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton_locationPanel.setBackground(new java.awt.Color(153, 255, 255));
        homeButton_locationPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        homeButton_locationPanel.setForeground(new java.awt.Color(51, 51, 51));
        homeButton_locationPanel.setText("Home");
        homeButton_locationPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton_locationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton_locationPanelActionPerformed(evt);
            }
        });
        locationPanel.add(homeButton_locationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        aboutButton_locationPanel.setBackground(new java.awt.Color(153, 255, 255));
        aboutButton_locationPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        aboutButton_locationPanel.setForeground(new java.awt.Color(51, 51, 51));
        aboutButton_locationPanel.setText("About Us");
        aboutButton_locationPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutButton_locationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButton_locationPanelActionPerformed(evt);
            }
        });
        locationPanel.add(aboutButton_locationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        contactButton_locationPanel.setBackground(new java.awt.Color(153, 255, 255));
        contactButton_locationPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        contactButton_locationPanel.setForeground(new java.awt.Color(51, 51, 51));
        contactButton_locationPanel.setText("Get in touch");
        contactButton_locationPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactButton_locationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactButton_locationPanelActionPerformed(evt);
            }
        });
        locationPanel.add(contactButton_locationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, -1));

        location_locationPanel.setBackground(new java.awt.Color(153, 255, 255));
        location_locationPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        location_locationPanel.setForeground(new java.awt.Color(51, 51, 51));
        location_locationPanel.setText("Locations");
        location_locationPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        location_locationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location_locationPanelActionPerformed(evt);
            }
        });
        locationPanel.add(location_locationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 120, -1));

        BackButton_Location.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackButton_Location.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exitWhite.png"))); // NOI18N
        BackButton_Location.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton_Location.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackButton_LocationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackButton_LocationMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackButton_LocationMousePressed(evt);
            }
        });
        locationPanel.add(BackButton_Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 50, 50));

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Homepage_Locations.jpg"))); // NOI18N
        locationPanel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 820, 490));

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Homepage_LocationsBack.gif"))); // NOI18N
        locationPanel.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));

        jLayeredPane1.add(locationPanel, "card5");

        getContentPane().add(jLayeredPane1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        // When the cursor is brought on the Back label button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.black);  //colour changes to white but is not yet applied
        exitLabel.setBorder(Label_Border);  //colour is now applied
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        // When the cursor is brought on the back label button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        exitLabel.setBorder(Label_Border);
    }//GEN-LAST:event_exitLabelMouseExited

    private void exitLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMousePressed
        //When the back label button on the Home panel is pressed
        System.exit(0);  //current form closes
    }//GEN-LAST:event_exitLabelMousePressed

    private void homeButton_homePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton_homePanelActionPerformed
        // When Home button on the Home panel is pressed, Home panel does not change to other panel and remains the same
         switchPanels(homePanel);
    }//GEN-LAST:event_homeButton_homePanelActionPerformed

    private void aboutButton_homePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButton_homePanelActionPerformed
        // When about us button on the Home panel is pressed, about us panel opens up
        switchPanels(aboutPanel);
    }//GEN-LAST:event_aboutButton_homePanelActionPerformed

    private void contactButton_homePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactButton_homePanelActionPerformed
        // When Contact button on the home us panel is pressed, contact panel opens up
           switchPanels(contactPanel);
    }//GEN-LAST:event_contactButton_homePanelActionPerformed

    private void location_homePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location_homePanelActionPerformed
        // TODO add your handling code here:
        switchPanels(locationPanel);
    }//GEN-LAST:event_location_homePanelActionPerformed

    private void exitLabel_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel_aboutMouseEntered
        // When the cursor is brought on the back label button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.white); 
        exitLabel_about.setBorder(Label_Border); 
    }//GEN-LAST:event_exitLabel_aboutMouseEntered

    private void exitLabel_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel_aboutMouseExited
        // When the cursor is moved away from the back label button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.black); 
        exitLabel_about.setBorder(Label_Border);  
    }//GEN-LAST:event_exitLabel_aboutMouseExited

    private void exitLabel_aboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel_aboutMousePressed
        System.exit(0);  //Current form closes
    }//GEN-LAST:event_exitLabel_aboutMousePressed

    private void homeButton_aboutPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton_aboutPanelActionPerformed
        switchPanels(homePanel);
    }//GEN-LAST:event_homeButton_aboutPanelActionPerformed

    private void aboutButton_aboutPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButton_aboutPanelActionPerformed
        switchPanels(aboutPanel);
    }//GEN-LAST:event_aboutButton_aboutPanelActionPerformed

    private void contactButton_aboutPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactButton_aboutPanelActionPerformed
        switchPanels(contactPanel);
    }//GEN-LAST:event_contactButton_aboutPanelActionPerformed

    private void location_aboutPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location_aboutPanelActionPerformed
        switchPanels(locationPanel);
    }//GEN-LAST:event_location_aboutPanelActionPerformed

    private void nextLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextLabelMousePressed
        // When start button is pressed
          new Getting_IN().setVisible(true);  //Form called Getting_In opens up
          this.dispose();  //current form closes
    }//GEN-LAST:event_nextLabelMousePressed

    private void nextLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextLabelMouseExited
        // When the cursor is moved away from the start label button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.white);   
        nextLabel.setBorder(Label_Border);   
    }//GEN-LAST:event_nextLabelMouseExited

    private void nextLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextLabelMouseEntered
        // When the cursor is brought on the start label button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.black);  
        nextLabel.setBorder(Label_Border);  
    }//GEN-LAST:event_nextLabelMouseEntered

    private void BackButton_ContactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton_ContactMouseEntered
        // When the cursor is brought on the back label button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.white);  
        BackButton_Contact.setBorder(Label_Border);  
    }//GEN-LAST:event_BackButton_ContactMouseEntered

    private void BackButton_ContactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton_ContactMouseExited
        // When the cursor is moved away from the back label button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.black);  
        BackButton_Contact.setBorder(Label_Border);
    }//GEN-LAST:event_BackButton_ContactMouseExited

    private void BackButton_ContactMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton_ContactMousePressed
        System.exit(0);  //Current form closes
    }//GEN-LAST:event_BackButton_ContactMousePressed

    private void homeButton_contactPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton_contactPanelActionPerformed
        switchPanels(homePanel);
    }//GEN-LAST:event_homeButton_contactPanelActionPerformed

    private void aboutButton_contactPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButton_contactPanelActionPerformed
        switchPanels(aboutPanel);
    }//GEN-LAST:event_aboutButton_contactPanelActionPerformed

    private void contactButton_contactPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactButton_contactPanelActionPerformed
        switchPanels(contactPanel);
    }//GEN-LAST:event_contactButton_contactPanelActionPerformed

    private void location_contactPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location_contactPanelActionPerformed
        switchPanels(locationPanel);
    }//GEN-LAST:event_location_contactPanelActionPerformed

    private void BackButton_LocationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton_LocationMouseEntered
        // When the cursor is brought on the back label button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.white);  
        BackButton_Location.setBorder(Label_Border); 
    }//GEN-LAST:event_BackButton_LocationMouseEntered

    private void BackButton_LocationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton_LocationMouseExited
        // When the cursor is moved away from the Back label-button
        Border Label_Border =  BorderFactory.createMatteBorder(1,1,1,1,Color.black); 
        BackButton_Location.setBorder(Label_Border);  
    }//GEN-LAST:event_BackButton_LocationMouseExited

    private void BackButton_LocationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton_LocationMousePressed
        System.exit(0);  // The current form closes
    }//GEN-LAST:event_BackButton_LocationMousePressed

    private void homeButton_locationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton_locationPanelActionPerformed
        switchPanels(homePanel);
    }//GEN-LAST:event_homeButton_locationPanelActionPerformed

    private void aboutButton_locationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButton_locationPanelActionPerformed
        switchPanels(aboutPanel);
    }//GEN-LAST:event_aboutButton_locationPanelActionPerformed

    private void contactButton_locationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactButton_locationPanelActionPerformed
        switchPanels(contactPanel);
    }//GEN-LAST:event_contactButton_locationPanelActionPerformed

    private void location_locationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location_locationPanelActionPerformed
        switchPanels(locationPanel);
    }//GEN-LAST:event_location_locationPanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel BackButton_Contact;
    private javax.swing.JLabel BackButton_Location;
    private javax.swing.JButton aboutButton_aboutPanel;
    private javax.swing.JButton aboutButton_contactPanel;
    private javax.swing.JButton aboutButton_homePanel;
    private javax.swing.JButton aboutButton_locationPanel;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel background_Label;
    private javax.swing.JButton contactButton_aboutPanel;
    private javax.swing.JButton contactButton_contactPanel;
    private javax.swing.JButton contactButton_homePanel;
    private javax.swing.JButton contactButton_locationPanel;
    private javax.swing.JPanel contactPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel exitLabel_about;
    private javax.swing.JButton homeButton_aboutPanel;
    private javax.swing.JButton homeButton_contactPanel;
    private javax.swing.JButton homeButton_homePanel;
    private javax.swing.JButton homeButton_locationPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel_aboutIn;
    private javax.swing.JPanel jPanel_contactIN;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel locationPanel;
    private javax.swing.JButton location_aboutPanel;
    private javax.swing.JButton location_contactPanel;
    private javax.swing.JButton location_homePanel;
    private javax.swing.JButton location_locationPanel;
    private javax.swing.JLabel nextLabel;
    // End of variables declaration//GEN-END:variables
}
