/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package martopediareal;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author zobia
 */
public class PaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() {
        initComponents();
        
        jPanel2.setBackground(new Color(255,255,255,200));  //Sets the BG colour of second panel to white
        
        expiryDate.setMinSelectableDate(new Date());  // Date chooser will allow only future dates to be selected   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cardNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cardVerification = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        expiryDate = new com.toedter.calendar.JDateChooser();
        cancelButton = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        billAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, -1, -1));

        cardNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cardNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNumberKeyTyped(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Card Number  ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(77, 81, 152));
        jLabel7.setText("PAYMENT");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Card Verification Number");

        cardVerification.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cardVerification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardVerificationKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Expiry Date");

        expiryDate.setDateFormatString("yyyy-MM-dd");

        cancelButton.setBackground(new java.awt.Color(255, 204, 231));
        cancelButton.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        paymentButton.setBackground(new java.awt.Color(129, 183, 210));
        paymentButton.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        paymentButton.setText("PAYMENT");
        paymentButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13)
                        .addComponent(cardVerification, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel5)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(expiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21)
                                .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardVerification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 470, 480));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Payment.jpg"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 560));

        billAmount.setText("jLabel1");
        jPanel1.add(billAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cardNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()))  //Only numbers can be typed
        {
            evt.consume();
        }
    }//GEN-LAST:event_cardNumberKeyTyped

    private void cardVerificationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardVerificationKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()))  //Only numbers can be typed
        {
            evt.consume();
        }
    }//GEN-LAST:event_cardVerificationKeyTyped

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        new Getting_IN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        // When Payment button is pressed
        // To get details from this form
        String Card_no = cardNumber.getText();
        String CV_no = cardVerification.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        String Date = dFormat.format(expiryDate.getDate());
        String Bill = billAmount.getText();
       
         //To get the email ID
         String email = UserInterface.emailLabel.getText();
         
         //To get Order Number
         String OrderNo = UserInterface.RandomNoLabel.getText();

        if(Card_no.isEmpty() && CV_no.isEmpty() )  //if fields on this form are Empty
        {
            JOptionPane.showMessageDialog(null,"PLEASE FILL ALL THE DETAILS");

        }
        else  if(Card_no.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"PLEASE FILL ALL THE DETAILS");
        }
        else  if(CV_no.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"PLEASE FILL ALL THE DETAILS");
        }
        else
        {
            try
            {

                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Martopedia","root","abc.123$");  //to establish relationship

                String Host = "smtp.gmail.com";  //application will send email to user through gmail
                String user = "smartmartopedia@gmail.com";  //application's email address
                String pass = "admin787";  //email's password

                String to = email;  //to get user's email ID from the form User_Booking
                String subject = "Order Confirmed";  //Subject of the mail application will send to the user

                //The below message is the message that will be written in the email that is sent to the user through Application
                String message = "We're glad you've placed an order through Martopedia! \n\nOrder Number - "+OrderNo+"\nTotal Bill - AED "+Bill
                        +"\nIn case you want to cancel your order please contact the store on the number provided. You will receive your order in 15 minutes."
                        +"\n\nYou can contact us for futher queries, if any, using your Order Number. We hope to meet your expectations. \n\nWarm Regards,\nTeam - Martopedia. ";

                // The lines of code below establishes a connection with gmail server so that our application can send the mail
                boolean sessionDebug = true;
                Properties property = System.getProperties();  // "Properties" is a built-in function of java and "property" is a variable declared
                property.put("mail.smtp.starttls.enable","true");
                property.put("mail.smtp.host","smtp.gmail.com");
                property.put("mail.smtp.port","587");
                property.put("mail.smtp.auth","true");
                property.put("mail.smtp.starttls.required","true");
                property.put("mail.smtp.socketFactory.port", "465");
                property.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
                property.put("mail.smtp.socketFactory.fallback", "false");

                java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
                Session mailSession = Session.getDefaultInstance(property, null);
                mailSession.setDebug(sessionDebug);
                Message msg = new MimeMessage(mailSession);
                msg.setFrom(new InternetAddress(user));
                InternetAddress [] address = {new InternetAddress(to)};
                msg.setRecipients(Message.RecipientType.TO,address);
                msg.setSubject(subject);
                msg.setText(message);
                Transport transport = mailSession.getTransport("smtp");
                transport.connect(Host, user, pass);
                transport.sendMessage(msg, msg.getAllRecipients());
                transport.close();  //Mail is sent

                JOptionPane.showMessageDialog(this,"Payment Done!\nPlease Check your mailbox for Confirmation." );  //this shows a pop up message that mail is sent

                //UserInterface opens up and the current form closes
                new Getting_IN().setVisible(true);
                this.dispose();

            }

            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }

        }

    }//GEN-LAST:event_paymentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    public static javax.swing.JLabel billAmount;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cardNumber;
    private javax.swing.JTextField cardVerification;
    private com.toedter.calendar.JDateChooser expiryDate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton paymentButton;
    // End of variables declaration//GEN-END:variables
}
