/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package martopediareal;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author zobia
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registeration
     */
    public Registration() {
        initComponents();
         emailID.setEditable(false);
    }
    
    int xx,xy;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        emailID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mobileNO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Address = new javax.swing.JTextArea();
        Name = new javax.swing.JTextField();
        ResetButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BG1 = new javax.swing.JLabel();
        BG2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BG3 = new javax.swing.JLabel();
        BG4 = new javax.swing.JLabel();
        BG5 = new javax.swing.JLabel();
        BG6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 470, 10));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registered Email ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(emailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 240, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile Number:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        mobileNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNOActionPerformed(evt);
            }
        });
        mobileNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobileNOKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileNOKeyTyped(evt);
            }
        });
        jPanel1.add(mobileNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 240, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        Address.setColumns(20);
        Address.setRows(5);
        Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AddressKeyTyped(evt);
            }
        });
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 240, 110));

        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameKeyTyped(evt);
            }
        });
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 240, 30));

        ResetButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ResetButton.setText("RESET");
        ResetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 100, -1));

        SubmitButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SubmitButton.setText("SUBMIT");
        SubmitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 240, 20));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 240, 20));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Name:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 240, 20));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 240, 20));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRATION DETAILS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 610, 60));

        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Glitter.gif"))); // NOI18N
        BG1.setText("jLabel4");
        jPanel1.add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 320));

        BG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Glitter.gif"))); // NOI18N
        jPanel1.add(BG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 130, 280));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        BG3.setForeground(new java.awt.Color(255, 255, 255));
        BG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Glitter.gif"))); // NOI18N
        jPanel1.add(BG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 500, 330));

        BG4.setForeground(new java.awt.Color(255, 255, 255));
        BG4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Glitter.gif"))); // NOI18N
        jPanel1.add(BG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 420, -1));

        BG5.setForeground(new java.awt.Color(255, 255, 255));
        BG5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Glitter.gif"))); // NOI18N
        jPanel1.add(BG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 420, -1));

        BG6.setForeground(new java.awt.Color(255, 255, 255));
        BG6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Glitter.gif"))); // NOI18N
        jPanel1.add(BG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 500, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mobileNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNOActionPerformed

    private void mobileNOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileNOKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNOKeyPressed

    private void mobileNOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileNOKeyTyped
        //when the user is typing the mobile number
        if(!Character.isDigit(evt.getKeyChar()))  //this makes sure that the user does not enter any character instead of numbers or mobile number
        {
            evt.consume();  //this will not allow the user to type any character
        }

        if (mobileNO.getText().length() >= 15 )   // this makes sure that the mobile number has not more than 15 numbers
        {
            evt.consume();  //otherwise user will not be able to type more numbers
        }

    }//GEN-LAST:event_mobileNOKeyTyped

    private void AddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddressKeyTyped
        // TODO add your handling code here:
        if (Address.getText().length() >= 50 )   // limit to 255 characters
        {
            evt.consume();
        }
    }//GEN-LAST:event_AddressKeyTyped

    private void NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyTyped
        // TODO add your handling code here:
        if (Name.getText().length() >= 20 )   // limit to 255 characters
        {
            evt.consume();
        }
    }//GEN-LAST:event_NameKeyTyped

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        //if reset button is clicked
        mobileNO.setText("");  //this clears anything written in the field
        Address.setText("");  //this clears anything written in the field
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        //When the submit button is pressed
        String email = emailID.getText();
        String name = Name.getText();
        String mobile = mobileNO.getText();
        String address = Address.getText();
        String Password= Getting_IN.jPasswordField1.getText();  //gets password from the Getting_In form and stores it in this variable

        if(name.isEmpty() && mobile.isEmpty() && address.isEmpty())  //If all these fields are empty then
        {
            jLabel14.setText("*REQUIRED ");     //these labels are placed below the textfields and
            jLabel15.setText("*REQUIRED ");    //will display message REQUIRED if these fields are empty
            jLabel16.setText("*REQUIRED ");   //and the submit button
            jLabel18.setText("*REQUIRED "); // is clicked
        }

        else if(name.isEmpty())
        {
            jLabel18.setText("*REQUIRED ");
        }
        else if(mobile.isEmpty())
        {
            jLabel15.setText("*REQUIRED ");
        }
        else if(address.isEmpty())
        {
            jLabel16.setText("*REQUIRED ");
        }
        else
        {
            try
            {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)
                DriverManager.getConnection ("jdbc:mysql://localhost:3306/Martopedia","root", "abc.123$");
                Statement stmt = (Statement) con.createStatement();

                String query="INSERT INTO User_Details VALUES('"+email+"','"+Password+"','"+name+"','"+mobile+"','"+address+"');"; //Inserts all the data given by the user into a table of  the database
                String query2="INSERT INTO AllUsers VALUES('"+email+"','"+Password+"');";  //stores this data into another table of the same database
                stmt.executeUpdate(query);
                stmt.executeUpdate(query2);

                JOptionPane.showMessageDialog(this,"Account Created & Details Registered Successfully!");  //Pop-up message is displayed showing success message
                new UserInterface().setVisible(true); 
                UserInterface.emailLabel.setText(emailID.getText());
                this.dispose();  //current form is closed
            }

            catch(Exception e)
            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }

        }

    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x,y;
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:

        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address;
    private javax.swing.JLabel BG1;
    private javax.swing.JLabel BG2;
    private javax.swing.JLabel BG3;
    private javax.swing.JLabel BG4;
    private javax.swing.JLabel BG5;
    private javax.swing.JLabel BG6;
    private javax.swing.JTextField Name;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SubmitButton;
    public static javax.swing.JTextField emailID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mobileNO;
    // End of variables declaration//GEN-END:variables
}
